### ISSUE TITLE
Nodes failing after apt upgrade

### ISSUE THREAD

**Issue by Fran-FC** [turtlebot/turtlebot4_robot#19]
**Please provide the following information:**
 - OS: Ubuntu 22.04
 - ROS Distro: Humble
 - Built from source or installed: installed
 - Package version: last version of turtlebot4. 1.0.1-1jammy.20230516.181141

 **Expected behaviour**
After running `sudo apt upgrade` a lot of ROS nodes fall into error.

 **Actual behaviour**
See journalctl output:

```
May 24 09:15:10 raspberry systemd[1]: turtlebot4.service: Failed with result 'exit-code'.
May 24 09:15:10 raspberry systemd[1]: turtlebot4.service: Main process exited, code=exited, status=1/FAILURE
May 24 09:15:10 raspberry turtlebot4-start[1787]: rclpy._rclpy_pybind11.InvalidHandle: cannot use Destroyable because destruction was requested
May 24 09:15:10 raspberry turtlebot4-start[1787]:     with self.handle:
May 24 09:15:10 raspberry turtlebot4-start[1787]:   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/client.py", line 159, in service_is_ready
May 24 09:15:10 raspberry turtlebot4-start[1787]:     while self.context.ok() and not self.service_is_ready() and timeout_sec > 0.0:
May 24 09:15:10 raspberry turtlebot4-start[1787]:   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/client.py", line 176, in wait_for_service
May 24 09:15:10 raspberry turtlebot4-start[1787]:     while not self.__rclpy_load_node_client.wait_for_service(timeout_sec=1.0):
May 24 09:15:10 raspberry turtlebot4-start[1787]:   File "/opt/ros/humble/lib/python3.10/site-packages/launch_ros/actions/load_composable_nodes.py", line 119, in _load_node
May 24 09:15:10 raspberry turtlebot4-start[1787]:     self._load_node(next_load_node_request, context)
May 24 09:15:10 raspberry turtlebot4-start[1787]:   File "/opt/ros/humble/lib/python3.10/site-packages/launch_ros/actions/load_composable_nodes.py", line 197, in _load_in_sequence
May 24 09:15:10 raspberry turtlebot4-start[1787]:     result = self.fn(*self.args, **self.kwargs)
May 24 09:15:10 raspberry turtlebot4-start[1787]:   File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
May 24 09:15:10 raspberry turtlebot4-start[1787]: Traceback (most recent call last):
May 24 09:15:10 raspberry turtlebot4-start[1787]: future: <Future finished exception=InvalidHandle('cannot use Destroyable because destruction was requested')>
May 24 09:15:10 raspberry turtlebot4-start[1787]: Future exception was never retrieved
May 24 09:15:10 raspberry turtlebot4-start[1787]: [ERROR] [launch]: Caught exception in launch (see debug for traceback): "package 'joint_state_publisher' not found, searching: ['/opt/ros/humble']"
May 24 09:15:05 raspberry turtlebot4-start[1787]: [INFO] [launch]: Default logging verbosity is set to INFO
May 24 09:15:05 raspberry turtlebot4-start[1787]: [INFO] [launch]: All log files can be found below /tmp/2023-05-24-09-15-05-973193-raspberry-1787
May 24 09:15:04 raspberry turtlebot4-start[1781]: ls: cannot access '/etc/ros/humble/turtlebot4.d/*.xacro': No such file or directory
May 24 09:15:03 raspberry systemd[1]: Started "bringup turtlebot4".
```

No laser scan output, nether linux_joy node working, these are the topics after upgrade:

```
/battery_state
/cmd_audio
/cmd_lightring
/cmd_vel
/dock_status
/hazard_detection
/imu
/interface_buttons
/ir_intensity
/ir_opcode
/kidnap_status
/mobility_monitor/transition_event
/mouse
/odom
/parameter_events
/robot_state/transition_event
/rosout
/slip_status
/static_transform/transition_event
/stop_status
/tf
/tf_static
/wheel_status
/wheel_ticks
/wheel_vels
```

**To Reproduce**
Provide the steps to reproduce:
1. run `sudo apt update; sudo apt upgrade -y`
2. restart the robot
3. see the error

Is there any way to revert the updates?

**Comment by Fran-FC** [comment]
Solved: after reflashing the latest image, I changed the repository from ` http://packages.ros.org/ros2-testing/ubuntu` to `http://packages.ros.org/ros2/ubuntu` in the file `/etc/apt/sources.list.d/ros2.list`. After upgrading everything works fine.

**Comment by Fran-FC** [comment]
It can be solved also running `sudo apt install ros-humble-joint-state-publisher` and then restarting the turtlebot4 service `sudo systemctl restart turtlebot4.service`

**Comment by roni-kreinin** [comment]
Looks like the `joint_state_publisher` dependency is missing in `turtlebot4_description`. I will add it and release a new version to fix this issue.
